# Generated by Django 4.1.2 on 2022-10-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0001_initial'),
        ('setup', '0010_alter_buyer_created_at_alter_style_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sewingDate', models.DateField()),
                ('workHour', models.PositiveSmallIntegerField(default=10)),
                ('dayTerget', models.PositiveSmallIntegerField(default=0)),
                ('hourTerget', models.PositiveSmallIntegerField(default=0)),
                ('LineWIP', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('operator', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('helper', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_8_9', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_9_10', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_10_11', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_11_12', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_12_13', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_14_15', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_15_16', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_16_17', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_17_18', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_18_19', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_19_20', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_20_21', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('H_21_22', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('DataLock', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('modified', models.DateField(auto_now=True)),
                ('Unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.unit')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
