# Generated by Django 4.1.2 on 2022-10-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='planID',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
