# Generated by Django 4.1.2 on 2022-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_datalock_production_datalock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='dataLock',
            field=models.CharField(max_length=2),
        ),
    ]
