# Generated by Django 4.1.2 on 2022-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_production_datalock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='dataLock',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=2, null=True),
        ),
    ]
