# Generated by Django 4.1.2 on 2022-10-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_production_datalock'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='totalProduction',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
