# Generated by Django 4.1.2 on 2022-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_production_totalproduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='dayTerget',
            new_name='dayTarget',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='hourTerget',
            new_name='hourTarget',
        ),
        migrations.AddField(
            model_name='production',
            name='achievementEfficiency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='production',
            name='dayAchievement',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='dotHour',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='manpower',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='runDay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='production',
            name='targetEfficiency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='production',
            name='vair',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
