# Generated by Django 4.1.2 on 2022-10-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_rename_dayterget_production_daytarget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='vair',
            new_name='vari',
        ),
    ]
