# Generated by Django 4.1.2 on 2022-10-19 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_unit_holiday'),
        ('production', '0008_rename_vair_production_vari'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.floor'),
        ),
        migrations.AddField(
            model_name='production',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.line'),
        ),
        migrations.AddField(
            model_name='production',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.style'),
        ),
    ]
