# Generated by Django 4.1.2 on 2022-10-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_production_floor_production_line_production_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='dotHour',
        ),
        migrations.RemoveField(
            model_name='production',
            name='totalProduction',
        ),
    ]
