# Generated by Django 4.1.2 on 2022-10-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_remove_production_dothour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='line',
        ),
    ]
