# Generated by Django 4.1.2 on 2022-10-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_unit_holiday'),
        ('production', '0011_remove_production_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.line'),
        ),
    ]
