# Generated by Django 4.1.2 on 2022-10-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='shortcut',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='shortcut',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='typeName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
