# Generated by Django 4.1.2 on 2022-10-12 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_floor_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 12, 54, 0, 50064)),
        ),
    ]
