# Generated by Django 4.1.2 on 2022-10-12 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_style_created_at_style_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='style',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 10, 12)),
        ),
    ]
