# Generated by Django 4.1.2 on 2022-10-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_buyer_created_at_alter_style_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='endDuty',
            field=models.PositiveSmallIntegerField(default=17, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='holiday',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='startDuty',
            field=models.PositiveSmallIntegerField(default=8, null=True),
        ),
    ]
