# Generated by Django 4.1.2 on 2022-10-12 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_unit_endduty_unit_holiday_unit_startduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='style',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='style',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
