# Generated by Django 4.1.2 on 2022-10-12 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_alter_buyer_created_at_alter_style_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 15, 43, 45, 698108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='style',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 15, 43, 45, 698331, tzinfo=datetime.timezone.utc)),
        ),
    ]
