# Generated by Django 4.1.2 on 2022-10-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_alter_buyer_created_at_alter_style_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='holiday',
            field=models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], default='4', max_length=1),
        ),
    ]
