# Generated by Django 4.1.2 on 2022-10-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_alter_unit_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='holiday',
            field=models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=1),
        ),
    ]
