# Generated by Django 4.1.2 on 2022-10-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_plan_orderqty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='Buyer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Style',
            new_name='style',
        ),
    ]
