# Generated by Django 4.1.2 on 2022-10-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_rename_buyer_plan_buyer_rename_style_plan_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='DataLock',
            new_name='dataLock',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Line',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Unit',
            new_name='unit',
        ),
    ]
