# Generated by Django 4.1.2 on 2022-10-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_rename_datalock_plan_datalock_rename_line_plan_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='orderQty',
            field=models.IntegerField(),
        ),
    ]
