# Generated by Django 4.1.2 on 2022-10-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_alter_plan_orderqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='DayID',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
