# Generated by Django 4.1.2 on 2022-10-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_plan_dayid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='DayID',
            new_name='planID',
        ),
    ]
