# Generated by Django 4.1.2 on 2022-10-14 06:04

from django.db import migrations, models
import plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_rename_dayid_plan_planid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.CharField(default=plan.models.increment_booking_number, max_length=150, null=True),
        ),
    ]
