# Generated by Django 4.1.2 on 2022-10-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_alter_plan_planid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='dataLock',
        ),
        migrations.AddField(
            model_name='plan',
            name='DataLock',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=2, null=True),
        ),
    ]
