# Generated by Django 4.1.2 on 2022-10-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_remove_plan_datalock_plan_datalock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='planQtyExtra',
            new_name='totalOrder',
        ),
    ]
