# Generated by Django 4.1.2 on 2022-10-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_rename_inputdate_plan_sewingstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='totalOrder',
            field=models.IntegerField(),
        ),
    ]
