# Generated by Django 4.1.2 on 2022-10-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_plan_planqtyextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='DataLock',
            new_name='dataLock',
        ),
    ]
