# Generated by Django 4.1.2 on 2022-10-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_floor_line'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.unit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='utype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.usertype'),
        ),
    ]
